### ISSUE TITLE
LyricsMania is returning a video instead of lyrics

### ISSUE THREAD

**Issue by phimath** [Smile4ever/LyricsCore#1]
LyricsMania is returning this as the lyrics:
`<div class="lyrics-body">↵<div id="video-musictory">↵<h5 style="font-size: 13px;">Compendium Video:</h5>↵<a href="http://www.musictory.com/music/Elder/Compendium" target="_blank" class="a-video" onclick="javascript: pageTracker._trackPageview('/videomusictory');" rel="nofollow"><img src="//i.ytimg.com/vi/wYhXBP6rFBk/0.jpg" border="0" class="thumb-video"><img src="/images/play2.png" class="play-video"></a>`

from this url: https://www.lyricsmania.com/compendium_lyrics_elder.html

**Comment by Smile4ever** [comment]
@phimath This has been fixed, thanks for reporting!

**Comment by phimath** [comment]
Thanks!
